-- Create Database
CREATE DATABASE `sms_based_quiz_demo`;

USE sms_based_quiz_demo;

-- Table structure for table `users`
CREATE TABLE `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `msisdn` char(15) NOT NULL,
  `registration_date` datetime NOT NULL,
  `user_status` char(1) NOT NULL DEFAULT '1',
  `last_activity_date` datetime NOT NULL,
  `last_question_id` int(11) NOT NULL DEFAULT '0',
  `user_score` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `msisdn_UNIQUE` (`msisdn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for table `activity_log`
CREATE TABLE `activity_log` (
  `activity_id` int(11) NOT NULL AUTO_INCREMENT,
  `msisdn` char(15) NOT NULL,
  `text_msg` varchar(500) DEFAULT NULL,
  `activity_date` datetime NOT NULL,
  PRIMARY KEY (`activity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for table `questions`
CREATE TABLE `questions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `question_id` int(11) NOT NULL,
  `full_question` varchar(500) NOT NULL,
  `word_count_full_question` int(11) NOT NULL,
  `question_english` varchar(300) NOT NULL,
  `question_bangla` varchar(500) NOT NULL,
  `word_count_bangla` int(11) NOT NULL,
  `option_a` varchar(100) NOT NULL,
  `option_a_bangla` varchar(200) NOT NULL,
  `option_b` varchar(100) NOT NULL,
  `option_b_bangla` varchar(200) NOT NULL,
  `answer` char(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rjc_questionscol_UNIQUE` (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table `questions`
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 1,'Bishawcup Trofir KargorItalir Silvi Gazzaniga kobe mara jan? A) 9/30/2007 B) 31 0ct 2016.Sothik answer A or B likhe send korun 16452 a',134,'Bishawcup Trofir KargorItalir Silvi Gazzaniga kobe mara jan?','বিশ্বকাপ ট্রফির কারিগর ইতালির সিলভি গাজ্জানিগা কবে মারা যান ? ',62,'39355','৩০ সেপ্টেম্বর ২০০৭','31 0ct 2016','৩১ অক্টোবর ২০১৬','B' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 2,'Tana ekadosh barer moto borsho shera swedish footballer k? A) Ibrahimovic B)Adam Gilcrist.Sothik answer A or B likhe send korun 16452 a',135,'Tana ekadosh barer moto borsho shera swedish footballer k?','টানা একাদশবারের মত বর্ষ সেরা সুইডিশ ফুটবলার কে ? ',49,'Ibrahimovic','ইব্রাহিমোভিচ  ','Adam Gilcrist','অ্যাডাম গ্রিলক্রিস্ট','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 3,'Australian player DIZZY  nick name ki? A) Jason Gillespe B)Adam Gilcrist. Sothik answer A or B likhe send korun 16452 a',119,'Australian player DIZZY  nick name ki?','অস্ট্রেলিয়ার খেলোয়ার ডিজির নিক নেইম কি?',39,'Jason Gillespe','জনশন গ্রিলক্রিস্ট','Adam Gilcrist','অ্যাডাম গ্রিলক্রিস্ট','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 4,'Prothom international cricket match hoy koto salay ? A) 1850 B)1844 . Sothik answer A or B likhe send korun 16452 a',115,'Prothom international cricket match hoy koto salay ?','প্রথম আন্তর্জাতিক ক্রিকেট ম্যাচ হয় কত সালে?',43,'1850','1850','1844','1844','B' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 5,'kon dui tem Prothom international cricket match khaly ? A) 1850 B)1844 . Sothik answer A or B likhe send korun 16452 a',118,'kon dui tem Prothom international cricket match khaly?','কোন দু’ই দল প্রথম আন্তর্জাতিক ক্রিকেট ম্যাচ শুরু করে?',53,'Canada and the USA','কানাডা ও অ্যামেরিকা','England and Australia','অস্ট্রেলিয়া ও ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 6,'Koto Sonay ICC cricket Start hoy?  A) 1980 B)1975. Sothik answer A or B likhe send korun 16452 a',96,'Koto Sonay ICC cricket Start hoy?','কত সালে আর্ন্তজাতিক ক্রিকেট খেলা শুরু হয়? ',42,'1980','1980','1975','1975','B' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 7,'Kon tem Bashie icc world joy love korchay ? A) Australia  B) England. Sothik answer A or B likhe send korun 16452 a',115,'Kon tem Bashie icc world joy love korchay ?','ক্রিকেটে কোন বেশি জয় লাভ করেছে ?',32,'Australia','অস্ট্রেলিয়া','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 8,'Australia ODI status koto sonay pai ? A) 1971  B) 1970. Sothik answer A or B likhe send korun 16452 a',101,' Australia ODI status koto sonay pai ?','অস্ট্রেলিয়া কত সালে ওয়ানডে স্ট্যার্টাস পায় ?',44,'1971','1971','1970','1970','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 9,'Pakistan  ODI status koto sonay pai ? A) 1986  B) 1987. Sothik answer A or B likhe send korun 16452 a',101,' Pakistan  ODI status koto sonay pai ?','পাকিস্তান কত সালে ওয়ানডে স্ট্যার্টাস পায় ?',42,'1986','1986','1987','1987','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 10,'kon team basi run Change koray joy paychay ? A) New Zealand  B) England. Sothik answer A or B likhe send korun 16452 a',118,'kon team basi run Change koray joy paychay?','কোন দল বেশি রান টপকে জিতছে ?',28,'New Zealand','নিউজিল্যান্ড','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 11,'Bangladesh ar mathay kon player mirto hoy ? A) Raman Lamba B) Subhash Gupte. Sothik answer A or B likhe send korun 16452 a',122,'Bangladesh ar mathay kon player mirto hoy ?','কোন খেলোয়ার বাংলাদেশের মাঠে মৃত্যু হয় ?',39,'Raman Lamba','রমন লাম্বা','Subhash Gupte','সুবাশ গুপ্তি','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 12,'kon wicket bowler pay na ? A) Run out  B) LBW. Sothik answer A or B likhe send korun 16452 a',92,'kon wicket bowler pay na ?','কোন উকেট বোলার পায় না ?',23,'Run out','রান আউট','LBW','এলবি','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 13,'koto over ay batting  power play ? A) 5  B) 7. Sothik answer A or B likhe send korun 16452 a',92,'koto over ay batting  power play ?','কত ওভারে বেটিং পাওয়ার প্লে ?',28,'5','5','7','7','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 14,'kon player 5 bochor ar jonno nishido Hoyachay  ? A) Mohammad Ashraful  B) Al amin Hossain. Sothik answer A or B likhe send korun 16452 a',136,'kon player 5 bochor ar jonno nishido Hoyachay ?','কোন খেলোয়ার ৫ বছরের জন্য নিষিদ্ধ হয়েছে ?',40,'Mohammad Ashraful ','মোহাম্মদ আশ্রাফুল ','Al amin Hossain','আল আমিন হোসেন','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 15,'Test cricket ay kom somay fiftay kay koray ? A) Misbah-ul-Haq  B) Mohammad Ashraful. Sothik answer A or B likhe send korun 16452 a',130,'Test cricket ay kom somay fiftay kay koray ?','টেস্ট ক্রিকেটে কে কম সময়ে অর্ধশত করে ?',38,'Misbah-ul-Haq','মেজবা উল হক','Mohammad Ashraful ','মোহাম্মদ আশ্রাফুল ','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 16,'Kay T20 tay duroto 100 run koray ? A) Richard Levi  B) Pollard. Sothik answer A or B likhe send korun 16452 a',109,'Kay T20 tay duroto 100 run koray ?','কে দ্রুততম T20 সেঞ্চুরি ?',25,'Richard Levi','রিচার্ড লিভি',' Pollard','পোলার্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 17,'Test ay Shakib Al Hasan 7 wicket kon team ar sathay ? A) New Zealand  B) India. Sothik answer A or B likhe send korun 16452 a',125,'Test ay Shakib Al Hasan 7 wicket kon team ar sathay ?','কোন দেশের সাথে সাকিব আল হাসান ৭টি উকেট পেয়েছে ?',47,'New Zealand','নিিউজিল্যান্ড','India','ভারত','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 18,' Australian national cricket team ar caps colour ki ? A)Green  B) Blue. Sothik answer A or B likhe send korun 16452 a',117,' Australian national cricket team ar caps colour ki ?','অস্ট্রেলিয়ার জাতীয় দলের ক্যাপের রং কি ?',39,'Green','গ্রীন','Blue ','ব্লু','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 19,'First icc world cup winer kon desh ? A) West Indies  B) England. Sothik answer A or B likhe send korun 16452 a',110,'First icc world cup winer kon desh ?','প্রথম বিশ্বকাপ ক্রিকেট জিতেছে কোন দেশ ?',39,'West Indies','অস্ট্রেলিয়া','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 20,'cricket ar vasay st ar manay ki ? A) Stumped  B) Dot Ball. Sothik answer A or B likhe send korun 16452 a',104,'cricket ar vasay st ar manay ki ?','ক্রিকেটের ভাষায় এসটি এর মানে কি?',32,' Stumped','স্ট্যাম্পেড','Dot Ball','ডট বল','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 21,'Test cricket a 10000 run prothom kay koran ? A) Gavaskar B) Lara. Sothik answer A or B likhe send korun 16452 a',111,'Test cricket a 10000 run prothom kay koran ?','টেস্ট ক্রিকেটে 10000 রান প্রথম কে করে ?',39,'Gavaskar','গাভাস্কার','Lara ','লারা','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 22,'LBW ar mani ki ? A) Leg before Wicket  B) Leg Break Wicket . Sothik answer A or B likhe send korun 16452 a',106,'LBW ar mani ki ?','LBW এর মানে কি ?',16,'Leg before Wicket','লেগ বিফর উইকেট','Leg Break Wicket ','লেগ ব্রেক উইকেট','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 23,'Glenn McGrath ar nickname ki ? A) Pigeon  B) Big Bird. Sothik answer A or B likhe send korun 16452 a',100,'Glenn McGrath ar nickname ki  ?','গ্রেল ম্যাকগ্যাথের ডাক নাম কি ?',31,'Pigeon','অস্ট্রেলিয়া','Big Bird','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 24,'Sachin Tendulkar kon desh ar player ? A) India  B) England. Sothik answer A or B likhe send korun 16452 a',105,'Sachin Tendulkar kon desh ar player ?','শচীন টেন্ডুলকার কোন দেশের খেলোয়ার ?',35,'India','ইন্ডিয়া','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 25,'Kon cricketer test ay prothom 300 wicket niyachan ? A) Fred Trueman   B) Wasim Akram. Sothik answer A or B likhe send korun 16452 a',131,'Kon cricketer test ay prothom 300 wicket niyachan ?','প্রথম কোন ক্রিকেটার ৩০০ উেইকেট নিয়েছেণ ?',40,'Fred Trueman ','ফ্রেড ট্রুম্যান','Wasim Akram','ওয়াসিম আকরাম','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 26,'Wasim Akram Kon desh ar player ? A) Pakistan   B) England. Sothik answer A or B likhe send korun 16452 a',104,'Wasim Akram Kon desh ar player ?','ওয়াসিম আকরাম কোন দেশের খেলোয়ার ?',32,'Pakistan','অস্ট্রেলিয়া','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 27,'Al Amin Hossain Kon desh ar player ? A) Australia  B) Bangladesh. Sothik answer A or B likhe send korun 16452 a',111,'Al Amin Hossain Kon desh ar player ?','আল আমিন হোসেন কোন দেশের খেলোয়ার ?',33,'Australia','অস্ট্রেলিয়া','Bangladesh','বাংলাদেশ','B' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 28,'Shakib Al Hasan  Kon desh ar player ? A) Australia  B) Bangladesh. Sothik answer A or B likhe send korun 16452 a',112,'Shakib Al Hasan  Kon desh ar player ?','সাকিব আল হাসান কোন দেশের খেলোয়ার ?',34,'Australia','অস্ট্রেলিয়া','Bangladesh','বাংলাদেশ','B' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 29,'Harbajan Singh middle name ki ? A) Australia  B) England. Sothik answer A or B likhe send korun 16452 a',103,'Harbajan Singh middle name ki ?','হরভজন সিং এর মিডিল নাম কি ?',27,'Plaha','পালাহা','Kholi','কলি','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 30,'Shakib Al Hasan ar bari kon District ay ‍? A) Magura  B) Dhaka. Sothik answer A or B likhe send korun 16452 a',109,'Shakib Al Hasan ar bari kon District ay ?','সাকিব আল হাসের বাড়ি কোন জেলাতে ?',32,'Magura','মাগুরা','Dhaka','ঢাকা','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 31,'Shakib Al Hasan ar jonmo son konta ? A) 1987  B) 1988. Sothik answer A or B likhe send korun 16452 a',100,'Shakib Al Hasan ar jonmo son konta ?','সাকিব আল হাসের জন্মসাল কত ?',27,'1987','1987','1988','1988','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 32,'Shakib Al Hasan ar bari kon Division ay ‍? A) Khulna  B) Dhaka. Sothik answer A or B likhe send korun 16452 a',109,'Shakib Al Hasan ar bari kon Division ay ?','সাকিব আল হাসের বাড়ি কোন বিভাগে?',31,'Khulna','খুলনা','Dhaka','ঢাকা','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 33,'Shakib Al Hasan IPL ar kon team ? A) Kolkata Knight Riders  B) Kings XI Punjab. Sothik answer A or B likhe send korun 16452 a',125,'Shakib Al Hasan IPL ar kon team ?','সাকিব আল হাসান আইপিএল এ কোন দলে ?',33,'Kolkata Knight Riders ','কলকাতা নাইট রাইডার্স','Kings XI Punjab','কিংস ইলেভেন পাঞ্জাব','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 34,'IPL ay total koyta team ? A) Australia  B) England. Sothik answer A or B likhe send korun 16452 a',97,'IPL ay total koyta team ?','আইপিএল মোট কতটি দল ?',20,'8','8','10','10','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 35,'Mustafizur Rahman IPL ar kon team ? A) Australia  B) England. Sothik answer A or B likhe send korun 16452 a',107,'Mustafizur Rahman IPL ar kon team ?','মোস্তাফিজুর রহমান আইপিএল এ কোন দলে ?',36,'Sunrisers Hyderabad','অস্ট্রেলিয়া','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 36,'Mustafizur Rahman  Kon desh ar player ? A) Australia  B) Bangladesh. Sothik answer A or B likhe send korun 16452 a',114,'Mustafizur Rahman  Kon desh ar player ?','মোস্তাফিজুর রহমান কোন দেশের খেলোয়ার ?',37,'Australia','অস্ট্রেলিয়া','Bangladesh','বাংলাদেশ','B' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 37,'Mustafizur Rahman ar bari kon District ay ‍? A) Satkhira  B) Dhaka. Sothik answer A or B likhe send korun 16452 a',113,'Mustafizur Rahma ar bari kon District ay ?','মোস্তাফিজুর রহমান বাড়ি কোন জেলাতে ?',35,'Satkhira','সাতক্ষীরা','Dhaka','ঢাকা','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 38,'Mustafizur Rahman  ar bari kon Division ay ‍? A) Khulna  B) Dhaka. Sothik answer A or B likhe send korun 16452 a',112,'Mustafizur Rahman ar bari kon Division ay ?','মোস্তাফিজুর রহমানের বাড়ি কোন বিভাগে?',36,'Khulna','খুলনা','Dhaka','ঢাকা','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 39,'Sachin Tendulkar ODI cricket koyti 100 korchay ? A) 49  B)50. Sothik answer A or B likhe send korun 16452 a',107,'Sachin Tendulkar ODI cricket koyti 100 korchay ?','শচীন টেন্ডুলকার ওয়ানডে ম্যাচে কয়টি ১০০ করেন ?',45,'49','49','50','50','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 40,'Sachin Tendulkar koyti icc world cup ay chilan ? A) 6  B) 8. Sothik answer A or B likhe send korun 16452 a',106,'Sachin Tendulkar koyti icc world cup ay chilan ?','শচীন টেন্ডুলকার কয়টি বিশ্বকাপে খেলেছেন ?',40,'6','6','7','7','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 41,'BD thakay 2011 kon player Wisden Test chilan? A) Tamim Iqbal  B) Habibul Basher. Sothik answer A or B likhe send korun 16452 a',126,'BD thakay 2011 kon player Wisden Test chilan ?','বাংলাদেশ থেকে ২০১১ সালে উইজডেন টেস্ট কে ছিলেন ?',47,'Tamim Iqbal ','তামিম ইকবাল','Habibul Basher','হাবিবুল বাসার','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 42,'2015 icc  world cup ay double centurion name ki ? A) Australia  B) England. Sothik answer A or B likhe send korun 16452 a',121,'2015 icc  world cup ay double centurion name ki ?','২০১৫ সালের আইসিসি বিশ্বকাপের ডাবল সেনচুরীয়ানের নাম কি ?',55,'Chris Gayle','ক্রিসগেইল','Hasim Amla','হাসিম আমলা','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 43,'Cricket ar pich ar dhorgho o prostho kot ? A) 22 goj o 10 ft  B) 20 goj o 12 ft. Sothik answer A or B likhe send korun 16452 a',126,'Cricket ar pich ar dhorgho o prostho kot ?','ক্রিকেট পিচ দৈঘ্য ও প্রস্হ কত ?',31,'22 goj o 10 ft','২২ গজ ও ১০ ফিট','20 goj o 12','২০ গজ ও ১২ ফিট','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 44,'Cricket boll ki diya toire ? A) Leather  B) wood. Sothik answer A or B likhe send korun 16452 a',95,'Cricket boll ki diya toire ?','ক্রিকেটে বল কি দিয়ে তৈরি ?',26,'Leather','লেদার','wood','কাঠ','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 45,'Cricket Stamp ar uchota koto ? A) 28 Ench  B) 30 Ench. Sothik answer A or B likhe send korun 16452 a',100,'Cricket Stamp ar uchota koto ?','ক্রিকেটে স্ট্যৈাম্পের উচ্চতা কত ?',33,'28','28','30','30','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 46,'Cricket ODI tay ekjon play ar koto over boll kortay paray  ? A) 10  B) 12. Sothik answer A or B likhe send korun 16452 a',120,'Cricket ODI tay ekjon play ar koto over boll kortay paray ?','ক্রিকেটে একজন বলার কত ওভার বলতে পারে ?',38,'10','10','12','12','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 47,'Kon player ODI tay  Duroto 150 kay ? A) AB de Villiers   B) England. Sothik answer A or B likhe send korun 16452 a',114,'Kon player ODI tay  Duroto 150 kay ?','কোন ক্রিকেটার একদিনের খেলায় ১৫০ রান করে ?',41,'AB de Villiers ','এবি ডি ভিলিয়ার্স','Tamim Iqbal','তামিম ইকবাল','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 48,'kay daba khela abiskar koray ? A) Sisa ben dahir B) Niyaz Morshed. Sothik answer A or B likhe send korun 16452 a',112,'kay daba khela abiskar koray ?','কে দাবা খেলা আবিস্কার করে ?',27,'Sisa ben dahir','সিসা বিন দাহির','Niyaz Morshed','নিয়ার্জ মোসেদ','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 49,'Bangladesh kar sathay 1st test match khelay ? A) India  B) England. Sothik answer A or B likhe send korun 16452 a',113,'Bangladesh kar sathay 1st test match khelay ?','বাংলাদেশ প্রথম টেস্ট ম্যাচ খেলে কার সাথে ?',42,'India','ভারত','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 50,'1st T-20 World cup hoy koto sonay ? A) 2007  B) 2008. Sothik answer A or B likhe send korun 16452 a',99,'1st T-20 World cup hoy koto sonay ?','প্রথম T20 বিশ্বকাপ কখন হয় ?',28,'2007','2007','2008','2008','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 51,'2016 Sonay T-20 cricket kothay hoy ? A) India  B) England. Sothik answer A or B likhe send korun 16452 a',104,'2016 Sonay T-20 cricket kothay hoy ?','২০১৬ সালে T20 ক্রিকেট কোথায় হয় ?',34,'India','ভারত','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 52,'2015 world cup ay man of the Tournament kay hoy ? A) Mitchell Starc  B) England. Sothik answer A or B likhe send korun 16452 a',126,'2015 world cup ay man of the Tournament kay hoy ?','২০১৫ সালে বিশ্বকাপে ম্যান অব দ্য টুর্নামেন্ট কে হয় ?',53,'Mitchell Starc','মিচেল স্টার্ক','AB de Villiers ','এবি ডি ভিলিয়ার্স','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 53,'Bangladesh 1st test a Captain kay ? A) Naimur Rahman Durjoy  B) Aminul Islam Bulbul. Sothik answer A or B likhe send korun 16452 a',130,'Bangladesh 1st test a Captain kay ?','বাংলাদেশের প্রথম টেস্ট অধিনায়ক কে ?',36,'Naimur Rahman Durjoy','নাঈমুর রহমান দুর্জয়','Aminul Islam Bulbul','আমিনুল ইসলাম বুলবুল','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 54,'sorbo konito test ay 100 koran kay ? A) Ashraful  B) Tamim Iqbal. Sothik answer A or B likhe send korun 16452 a',111,'sorbo konito test ay 100 koran kay ?','বিশ্বের সর্বকনিষ্ঠ টেস্ট সেঞ্চুরীয়ান কে ?',42,'Ashraful','আশরাফুল','Tamim Iqbal','তামিম ইকবাল','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 55,'ICC Champing ki hisabay porichito? A) 2nd world cup  B)  3rd world cup. Sothik answer A or B likhe send korun 16452 a',117,'ICC Champing ki hisabay porichito ?','ICC চ্যাম্পিয়ন ট্রফি কি হিসাবে পরিচিত ?',40,' 2nd world cup','ক্রিকেটের ২য় বিশ্বকাপ','3rd world cup','ক্রিকেটের য় বিশ্বকাপ','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 56,'2016 Sonay asis cup cricket kotha hoy ? A) Bangladesh  B) England. Sothik answer A or B likhe send korun 16452 a',112,'2016 Sonay asis cup cricket kotha hoy ?','২০১৬ এশিয়া কাপ ক্রিকেট কোথায় হয় ?',36,'Bangladesh','বাংলাদেশ','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 57,'Protham koto sonay &T-20 Khela hoy ? A) 2005  B) 2006. Sothik answer A or B likhe send korun 16452 a',100,'Protham koto sonay &T-20 Khela hoy ?','প্রথম স্বীকৃত টুয়েন্টি ২০ ম্যাচ অনুষ্ঠিত হয় ?',47,'2005','2005','2006','2006','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 58,'Prothom T-20 World cup hoy ? A) 11-24 Sept 2007  B) 20-30 Sept 2007. Sothik answer A or B likhe send korun 16452 a',114,'Prothom T-20 World cup hoy ?','প্রথম টুয়েন্টি ২০ বিশ্বকাপ ক্রিকেট অনুষ্ঠিত হয় ?',50,'11-24 Sept 2007','১১-২৪ সেপ্টেম্বর ২০০৭','20-30 Sept 2007','২০-৩০ সেপ্টেম্বর ২০০৭','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 59,'International T20 1st 100 kay koran ? A) Chris Gayle  B) Shakib Al Hasan Sothik answer A or B likhe send korun 16452 a',118,' International T20 1st 100 kay koran ?','আন্তরর্জাতিক টুয়েন্টি২০ ক্রিকেটে প্রথম সেঞ্চুরিয়ান?',53,'Chris Gayle','ক্রিস গেইল ','Shakib Al Hasan','সাকিব আল হাসান','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 60,'T20 Cricket 1st Hat-trick kon bolar ? A) Brett Lee B) Al amin Hossain. Sothik answer A or B likhe send korun 16452 a',116,'T20 Cricket 1st Hat-trick kon bolar ?',' টুয়েন্টি২০ ক্রিকেটে প্রথম হ্যাটট্রিককারী বোলার ?',50,'Brett Lee',' ব্রেট লি','Al amin Hossain','আল আমিন হোসেন','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 61,'3rd T 20 World Champion kon dol ? A) Australia  B) England. Sothik answer A or B likhe send korun 16452 a',105,'3rd T 20 World Champion kon dol ?','তৃতীয় টুয়েন্টি২০ বিশ্বকাপ ক্রিকেটের চ্যাম্পিয়ন ?',51,'Australia','অস্ট্রেলিয়া','England','ইংল্যান্ড','B' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 62,'3rd T 20 World Runners up kon dol ? A) Australia  B) England. Sothik answer A or B likhe send korun 16452 a',107,'3rd T 20 World Runners up kon dol ?','তৃতীয় টুয়েন্টি২০ বিশ্বকাপ ক্রিকেটের রানার্স আপ ?',50,'Australia','অস্ট্রেলিয়া','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 63,'1st T 20 World cup Champion kon dol ? A) India  B) England. Sothik answer A or B likhe send korun 16452 a',105,'1st T 20 World cup Champion kon dol ?','প্রথম টুয়েন্টি ২০ বিশ্বকাপ ক্রিকেটের চ্যাম্পিয়ন ?',51,'India','ভারত','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 64,'1st T 20 World cup Runners up kon dol ? A) India  B) Pakistan. Sothik answer A or B likhe send korun 16452 a',108,'1st T 20 World cup Runners up dol ?','প্রথম টুয়েন্টি ২০ বিশ্বকাপ ক্রিকেটের রানার্স আপ ?',50,'India','ভারত','Pakistan','পাকিস্তান','B' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 65,'T 20 World cup koto bochor por hoy ? A) 2  B) 3. Sothik answer A or B likhe send korun 16452 a',94,'T 20 World cup koto bochor por hoy ?','টুয়েন্টি২০ বিশ্বকাপ ক্রিকেট অনুষ্ঠিত হয় কয় বছর পর ?',53,'2','2','3','3','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 66,'4th T 20 world cup cricket Onusthito hoy ? A) Sri Lanka  B) England. Sothik answer A or B likhe send korun 16452 a',114,'4th T 20 world cup cricket Onusthito hoy ?','চতুর্থ টুয়েন্টি২০ বিশ্বকাপ ক্রিকেট অনুষ্ঠিত হয় ?',49,'Sri Lanka','শ্রীলংকায়','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 67,'T 20 World Cup ay sobochi run kar? A) Mahela jayabardhane  B) Brett Lee. Sothik answer A or B likhe send korun 16452 a',118,'T 20 World Cup ay sobochi run kar ?','টি ২০ বিশ্বকাপে ক্রিকেটের সর্বাধিক রানের অধিকারী  ?',51,'Australia','মাহেলা জয়াবর্ধানে ','Brett Lee','ব্রেট লি','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 68,'T 20 World Cup ay sobochi Wicket kar ‍? A) Shahid Afridi  B )Shakib Al Hasan. Sothik answer A or B likhe send korun 16452 a',123,'T 20 World Cup ay sobochi Wicket kar ?','টি ২০ বিশ্বকাপে ক্রিকেটের সর্বাধিক উকেটেরে অধিকারী  ?',53,'Shahid Afridi','শহীদ আফ্রিদি ','Shakib Al Hasan','সাকিব আল হাসান','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 69,'Mahela jayabardhane kon desh ar player ? A) Srilaka B) England. Sothik answer A or B likhe send korun 16452 a',109,'Mahela jayabardhane kon desh ar player  ?','মাহেলা জয়াবর্ধানে কোন দেশের খেলোয়ার ?',38,'Sri Lanka','শ্রীলংকা','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 70,'Asia Cup kobay thak suru hoy ? A) 1983  B) 1985. Sothik answer A or B likhe send korun 16452 a',94,'Asia Cup kobay thak suru hoy ?','এশিয়ান ক্রিকেট কবে থেকে শুরু হয় ?',34,'1983','1983','1985','1985','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 71,'Asia Cup koyti dol ongsogorhon kray ? A) 22  B) 24. Sothik answer A or B likhe send korun 16452 a',97,'Asia Cup koyti dol ongsogorhon kray ?','এশিয়া কাপে কয়টি দল অংশ গ্রহন করে ?',34,'22','22','24','22','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 72,'Asia cricket ar doptor kothay ? A) Kuala Lumpur  B) England. Sothik answer A or B likhe send korun 16452 a',106,'Asia cricket ar doptor kothay?','এশিয়ান ক্রিকেট কাউন্সিল (ACC)-এর সদর দপ্তর ?',45,'Kuala Lumpur','কুয়ালামপুর','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 73,'Asia Cup kobay start hoy ? A)1983 84  B) 1986 87. Sothik answer A or B likhe send korun 16452 a',95,'Asia Cup kobay start hoy ?','প্রথম এশিয়া কাপ ক্রিকেট অনুষ্ঠিত হয় ?',39,'1983 84','১৯৮৩ ৮৪','1986 87','১৯৮৬ ৮৭','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 74,'Protho asis cup win kon dol ? A) India  B) England. Sothik answer A or B likhe send korun 16452 a',97,'Protho asis cup win kon dol ?','প্রথম এশিয়ান ক্রিকেট কোন চ্যাম্পিয়ন হয় ?',42,'India','ভারত','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 75,'2010 sonay asis cup ay kon dol win hoy ? A) India  B) England. Sothik answer A or B likhe send korun 16452 a',108,'2010 sonay asis cup ay kon dol win hoy ?','২০১০ সালে এশিয়া কাপ ক্রিকেটে চ্যাম্পিয়ন হয়  ?',48,'India','ভারত','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 76,'19 tom Football Khela hoy ? A) 2010 B) 2015. Sothik answer A or B likhe send korun 16452 a',90,'19 tom Football Khela hoy ?','১৯তম বিশ্বকাপ ফুটবল অনুষ্ঠিত হয়  ?',35,'2010','2010','2015','2015','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 77,'19 tom Football Khela kothay hoy ? A) South Africa  B) England. Sothik answer A or B likhe send korun 16452 a',109,'19 tom Football Khela kothay hoy ?','১৯তম বিশ্বকাপ ফুটবল অনুষ্ঠিত হয় কোথায়  ?',41,'South Africa','দক্ষিণ আফ্রিকা','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 78,'19 tom Football Khela Finel mach hoy hoy ? A)11 July 2010  B) 20 July 2010. Sothik answer A or B likhe send korun 16452 a',121,'19 tom Football Khela Finel mach hoy hoy ?','১৯তম বিশ্বকাপ ফুটবলের ফাইনাল ম্যাচ হয় ?',40,'40370','১১ জুলাই ২০১০','40379','২০ জুলাই ২০১০','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 79,'19 tom Football Khela Finel mach hoy kon Stadium ay ? A) Johannesburg  B) 20 July 2010. Sothik answer A or B likhe send korun 16452 a',133,'19 tom Football Khela Finel mach hoy kon Stadium ay ?','১৯তম বিশ্বকাপ ফুটবলের ফাইনাল ম্যাচ হয় কোন স্টেডিয়ামে?',55,'Johannesburg','জোহানেসবার্গ','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 80,'19 tom Football Khela win hoy kon dol  ? A) Spain  B) England. Sothik answer A or B likhe send korun 16452 a',108,'19 tom Football Khela win hoy kon dol ?','১৯তম বিশ্বকাপ ফুটবলে চ্যাম্পিয়ন হয় ?',38,'Spain','স্পেন','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 81,'19 tom Football Khela Runners-up hoy kon dol  ? A) Spain  B) England. Sothik answer A or B likhe send korun 16452 a',115,'19 tom Football Khela Runners-up hoy kon dol ?','১৯তম বিশ্বকাপ ফুটবলে রানার্স আপহয় ?',36,'Netherlands','নেদারল্যান্ডস','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 82,'2010 sony world footbal ay sayra player kay hoy ? A) Diego phoralana  B)Jidan. Sothik answer A or B likhe send korun 16452 a',124,'2010 sony world footbal ay sayra player kay hoy ?','২০১০ সালের বিশ্বকাপের সেরা খেলোয়াড়ের কে পায়?',46,'Diego phoralana','দিয়েগো ফোরলান','Jidan','জিদান','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 83,'Diego phoralana kon desh ar player ? A) Uruguay  B) England. Sothik answer A or B likhe send korun 16452 a',106,'Diego phoralana kon desh ar player?','দিয়েগো ফোরলান কোন দেশের খেলোয়ার ?',34,'Uruguay','উরুগুয়ে','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 84,'2010 worl cup sayra gol data kay ? A) Thomas Muller  B) Messi. Sothik answer A or B likhe send korun 16452 a',108,'2010 worl cup sayra gol data kay ?','২০১০ বিশ্বকাপের সেরা গোলদাতার পুরষ্কার কে ?',43,'Thomas Muller','থমাস মুলার','Messi','মেসি','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 85,'Thomas Muller kon desh ar player ? A) Germany  B) England. Sothik answer A or B likhe send korun 16452 a',104,'Thomas Muller kon desh ar player  ?','থমাস মুলার কোন দেশের খেলোয়ার ?',30,'Germany','জার্মানি','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 86,'Thomas Muller koyti gol koray ? A) 5  B) 6. Sothik answer A or B likhe send korun 16452 a',89,'Thomas Muller koyti gol koray?','থমাস মুলার কয়টা গোল করে ?',25,'5','5','6','6','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 87,'2010 sonay sera torun player ke? Thomas Muller  B) Messi. Sothik answer A or B likhe send korun 16452 a',103,'2010 sonay sera torun player ke ?','২০১০ সালের সেরা তরুণ ফুটবলার  ?',31,'Thomas Muller','থমাস মুলার','Messi','মেসি','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 88,'2010 sonay world cup football 1st gol kay koray ? A) Siphiui sabalala B) Messi. Sothik answer A or B likhe send korun 16452 a',125,'2010 sonay world cup football 1st gol kay koray ?','২০১০ সালের বিশ্বকাপ ফুটবলে প্রথম গোল করেন কে ?',46,'Siphiui sabalala','সিফিউই শাবালালা','Messi','মেসি','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 89,'2010 sonay world cup football Hat-trick key koray ? A) Gonzalo higuyaina  B) Messi. Sothik answer A or B likhe send korun 16452 a',129,'2010 sonay world cup football Hat-trick key koray ?','২০১০ সালের বিশ্বকাপ ফুটবলে প্রথম হ্যাটট্রিক কে করে ?',52,'Gonzalo higuyaina','গঞ্জালো হিগুয়াইন','Messi','মেসি','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 90,'Football khalay jonmo kothay  ? A) Chain B) England. Sothik answer A or B likhe send korun 16452 a',98,'Football khalay jonmo kothay ?','ফুটবল খেলার জন্ম কোথায় ?',24,'Chain','চীনে ','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 91,'world ay pranchin football club ar name ? A) Englands Sheffield Football Club  B) England. Sothik answer A or B likhe send korun 16452 a',136,'world ay pranchin football club ar name?','বিশ্বের প্রাচীনতম ফুটবল ক্লাবের নাম ?',37,'Englands Sheffield Football Club','ইংল্যান্ডের শেফিল্ড ফুটবল ক্লাব ','Germany ','র্জামানি','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 92,'Prothom  football club hoy koto sonay ? A) 1857  B) 1860. Sothik answer A or B likhe send korun 16452 a',103,'Prothom  football club hoy koto sonay  ?','প্রথম ফুটবল ক্লাব কত সালে হয় ?',30,'1857','1857','1860','1860','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 93,'World Football Prodhan ar name ? A) FIFA  B) EIEA. Sothik answer A or B likhe send korun 16452 a',96,'World Football Prodhan ar name ?','বিশ্ব ফুটবলের প্রধান সংস্থার নাম  ?',35,'FIFA','ফিফা','EIEA','ইয়া','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 94,'FIFA-Full name ki? A) Federation int Football Association B) Eederation Int Eootball Association.Sothik answer A or B likhe send korun 16452 a',142,'FIFA-Full name ki ?','FIFA-এর পূর্ণরূপ  ?',19,'Federation Int Football Association','ফিফা','Eederation Int Eootball Association','ইয়া','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 95,'FIFA Jonmo Kobay ? A) 1904  B) 1910. Sothik answer A or B likhe send korun 16452 a',82,'FIFA Jonmo Kobay ?','FIFA- কত সালে ?',15,'1904','1904','1910','1910','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 96,'FIFA- Jonmo kon desh ? A) France  B) England. Sothik answer A or B likhe send korun 16452 a',91,'FIFA- Jonmo kon desh ?','FIFA-জন্মলাভ কোন দেশে ?',23,'France','ফ্রান্স','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 97,'FIFA ar Sodor doftor kothay ? A) Switzerland  B) England. Sothik answer A or B likhe send korun 16452 a',103,'FIFA ar Sodor doftor kothay ?','ফিফার সদর দপ্তর  কোথায় ?',24,'Switzerland','সুইজারল্যান্ড','England','ইংল্যান্ড','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 98,'FIFA Prothom Member koyjo chilo ? A) 7  B) 8. Sothik answer A or B likhe send korun 16452 a',91,'FIFA Prothom Member koyjo chilo ?','ফিফার প্রতিষ্ঠাতা সদস্য দেশ কয়টি ?',34,'7','7','8','8','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 99,'FIFA ar Member bortomay koyjon  ? A) 208  B) 210. Sothik answer A or B likhe send korun 16452 a',95,'FIFA ar Member bortomay koyjon ?','ফিফার বর্তমান সদস্য সংখ্যা কয়টি ?',33,'208','208','210','210','A' );
INSERT INTO `sms_based_quiz_demo`.`questions` (`question_id`,`full_question`,`word_count_full_question`,`question_english`,`question_bangla`,`word_count_bangla`,`option_a`,`option_a_bangla`,`option_b`,`option_b_bangla`,`answer`) VALUES ( 100,'FIFA ar Presient 1998 sonay kay chilan ? A) Sepp Blatter B) Meradona. Sothik answer A or B likhe send korun 16452 a',115,'FIFA ar Presient 1998 sonay kay chilan ?','ফিফার সভাপতি ১৯৯৮ সালে কে ছিলেন ?',33,'Sepp Blatter','সেপ ব্লাটার ','Meradona','ম্যারাডোনা','A' );
